### ISSUE TITLE
Is this the same as nvidia ngx upscaling?

### ISSUE THREAD

**Issue by Ulf3000** [dynamiquel/NVIDIA-Ansel-AI-Enhancer#1]
https://developer.nvidia.com/rtx/ngx

Didi you implement this? your app needs more exposure , i posted it to blender discord for upscaling renders

**Comment by dynamiquel** [comment]
I have nothing to do with NVIDIA NGX, but I would assume the 'up-scaling' part of NVIDIA NGX is some implentation of Ansel AI. Thanks for the post.

https://www.nvidia.com/en-us/geforce/news/new-gfe-features-latest-games-get-ansel-and-highlights/
