### ISSUE TITLE
rtx 3090 error

### ISSUE THREAD

**Issue by dylanjmartin** [dynamiquel/NVIDIA-Ansel-AI-Enhancer#3]
i cant use this program with an rtx 3090 i get system.io.filenotfoundexception 
Edit: heres the full error message
https://ibb.co/HhS1sXz

**Comment by dynamiquel** [comment]
Thanks for the full error. It doesn't appear to be an issue with your graphics card. The program seems to think that the file you selected doesn't actually exist.
My only guesses are:
1. the file is being protected through some anti-virus software.
2. the file isn't actually on your device but is on OneDrive.
3. the file was deleted after selecting it.

**Comment by dylanjmartin** [comment]
thats strange ive disabled my anti virus, ive moved drives and even reinstalled my drivers with no luck
EDIT: It would appear to have been the windows 10 insider build i was on it fixed itself after a few updates
