### ISSUE TITLE
umm im new to git

### ISSUE THREAD

**Issue by OlympicAngel** [dynamiquel/NVIDIA-Ansel-AI-Enhancer#5]
so hey im kinda new to git,
but anyway i have added somw staff to the code,
and i wonder how can i upload it so you can maybe add it so everyone can use it (if its even possible haha)

so yea i have added more upscale options in the deopdown,

added a checkbox of "limit image size" wich will well.. limit images size if it goes above 8Kpx (it will lower the scale factor to the max rounded posibble as it seems Answel cant take double values),

and finally an attempt to save transparency of an images,
currently it will convert transparent image to none transparent image in wich the alpha values are black.

my method is to upsacle the photo twitce, 
1 as normal,
2 before the upsacle - scan the eahc pixel in the original photo and creating with that data a new B&W images, represnting the alpha within the image, black = fully trans(alpha = 0), white (alpha = 255).
now upsacle the images the same way as the first,
and then merging the 2 images to create new image with the pixel data of the colored upscled & alpha data from the B&W upscale.
(btw it will do it only if the image has transparent values so normal images it will just skip it)

currently it is slower(depends of the image and scale factor) but still usable and atleast for me its better and faster then other sites or software..

also i want to upload it so maybe someone here knows a better way to merge the pixels in faster way.

so yea.. how can i do so?

**Comment by dynamiquel** [comment]
To learn how to create a pull request: https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

The transparency feature does sound really cool and will surely be beneficial to some users.

**Comment by OlympicAngel** [comment]
Thanx!
So because i dont have permissions here i just need to fork it and then you can review it and merge it, right?
(if yes i will get home in fue hours and will do it)
